security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UsersAuthenticator

            logout:
                path: app_logout
                target: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false

    access_control:
        - path: '^/login$'
          roles: PUBLIC_ACCESS

        - path: '^/[a-z]{2}/login$'
          roles: PUBLIC_ACCESS

        - path: '^/register'
          roles: PUBLIC_ACCESS

        - path: '^/[a-z]{2}/register'
          roles: PUBLIC_ACCESS

        - path: '^/reset-password'
          roles: PUBLIC_ACCESS

        - path: '^/admin'
          roles: ROLE_ADMIN

        - path: '^/[a-z]{2}/admin'
          roles: ROLE_ADMIN

        - path: '^/admissions/manage'
          roles: ROLE_ADMISSIONS

        - path: '^/[a-z]{2}/admissions/manage'
          roles: ROLE_ADMISSIONS

        - path: '^/faculty/manage'
          roles: ROLE_FACULTY

        - path: '^/[a-z]{2}/faculty/manage'
          roles: ROLE_FACULTY

        - path: '^/student'
          roles: ROLE_STUDENT

        - path: '^/[a-z]{2}/student'
          roles: ROLE_STUDENT

    role_hierarchy:
        ROLE_ADMISSIONS: ROLE_USER
        ROLE_FACULTY: ROLE_USER
        ROLE_STUDENT: ROLE_USER
        ROLE_ADMIN:
            - ROLE_ADMISSIONS
            - ROLE_FACULTY
            - ROLE_STUDENT
            - ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
